### ISSUE TITLE
Erscheinen des Klötzchens zu früh

### ISSUE THREAD

**Issue by birtecaesar** [hsu-aut/PLC-Simulation#2]
Ich habe die Initialisierung getestet und das harmonisiert optisch nicht ganz mit der Simulation. Denn sobald die Simulation gestartet wird, wird ein Klötzchen auf dem Förderband platziert. Das Klötzchen wird dann bereits bei der Initialisierung auf dem ersten Förderband nach vorne bewegt. 

Am Besten wäre es, wenn erst ein Klötzchen erscheint, wenn der Schalter B1_S06 getätigt wurde. 

Ist aber nur ein nice-to-have, da es bei meiner Implementierung nicht gestört hat ;)

**Comment by aljoshakoecher** [comment]
Ja, das Problem hatte ich noch auf dem Zettel... Beim Starten der Simulation wird der Schalter nicht abgefragt. Hab nicht dran gedacht, dass das natürlich für die Initialisierung problematisch ist
