### ISSUE TITLE
Reset-Knopf braucht ewig oder macht nichts

### ISSUE THREAD

**Issue by artanmarkaj** [hsu-aut/PLC-Simulation#3]
Zum Resetten der Simulation ist es einfacher dieser zu schließen und neuzustarten, als über den Reset-Knopf.

Was genau macht der Button im Hintergrund, dass es manchmal ewig dauert, abstürzt oder garnichts passiert?

**Comment by Alaettin** [comment]
Der Reset-Button funktioniert nur, wenn du die Simulation gestoppt hast!

**Comment by artanmarkaj** [comment]
Ich meinte eher, dass sich manchmal die Simulation aufhängt beim Drücken des Reset-Buttons.

**Comment by aljoshakoecher** [comment]
Okay... Dass die Simulation sich aufhängt, hatte ich beim Resetten noch nie. Kannst du da genauere Infos geben, was du gerade gemacht hast? Bzw. was die Simulation gemacht hat.

**Comment by aljoshakoecher** [comment]
Das Problem konnte anscheinend ja doch eher auf die Ungeduld des Benutzers (😉 ) zurückgeführt werden, daher schließe ich den Issue mal...
