### ISSUE TITLE
Übergabe Klotz zwischen Drehtisch und FB6 geht nicht

### ISSUE THREAD

**Issue by Alexander-Hayward** [hsu-aut/PLC-Simulation#4]
Aus irgendwelchen Gründen bleibt nach dem Drehen des Drehtisches und dem Anschalten des Transportbandes vom Drehtisch sowie dem Transportband von FB5 der Klotz am Ende des Drehtisches liegen. Auch ist mir aufgefallen, dass der Sensor B1_S09 nicht wieder ausgeht. Siehe Bild:

![image](https://user-images.githubusercontent.com/65892013/83136693-33321b00-a0e8-11ea-9276-755a6bfebe98.png)

**Comment by aljoshakoecher** [comment]
Schaue ich mir an. Hat die Farbunterscheidung vorher denn funktioniert oder hast du den Drehtisch "einfach so" gedreht?

**Comment by Alexander-Hayward** [comment]
> Schaue ich mir an. Hat die Farbunterscheidung vorher denn funktioniert oder hast du den Drehtisch "einfach so" gedreht?

> Die Farbunterscheidung über die Variable Zaehler hat bis dahin funktioniert!

**Comment by Alexander-Hayward** [comment]
Ich habe den Drehtisch daher ganz normal während des planmäßigen Transport des Teils gedreht und danach das Transportband aktiviert. Bis zum Ende des Tischs wurde der Klotz ja auch gebracht.
